HPCC-30888 support ECLIDE build with github action Also add code sign for Windows builds

diff --git a/.github/workflows/build-assets.yml b/.github/workflows/build-assets.yml
--- a/.github/workflows/build-assets.yml
+++ b/.github/workflows/build-assets.yml
@@ -190,7 +190,7 @@ jobs:
             type=registry,ref=${{ steps.vars.outputs.docker_tag }}
           cache-to: type=inline
 
-      # Communtiy Build 
+      # Communtiy Build
       - name: CMake Packages (community)
         if: ${{ !matrix.ln && !matrix.container && !matrix.documentation }}
         run: |
@@ -202,10 +202,10 @@ jobs:
             sudo rm -rf ${{ needs.preamble.outputs.folder_build }}/CMakeFiles
             docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "${{ needs.preamble.outputs.gpg_import }} && \
               cmake -S /hpcc-dev/HPCC-Platform -B /hpcc-dev/build ${{ needs.preamble.outputs.cmake_docker_config }} -DSIGN_MODULES_PASSPHRASE=${{ secrets.SIGN_MODULES_PASSPHRASE }} -DSIGN_MODULES_KEYID=${{ secrets.SIGN_MODULES_KEYID }} -D$plugin=ON -DCONTAINERIZED=OFF -DCPACK_STRIP_FILES=OFF ${{ matrix.cmake_options_extra }} && \
-              cmake --build /hpcc-dev/build --parallel $(nproc) --target package" 
+              cmake --build /hpcc-dev/build --parallel $(nproc) --target package"
             # Disabled as not currently needed ---
             # docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "cmake -S /hpcc-dev/HPCC-Platform -B /hpcc-dev/build ${{ needs.preamble.outputs.cmake_docker_config }} -D$plugin=ON -DCONTAINERIZED=OFF -DCPACK_STRIP_FILES=ON"
-            # docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "cmake --build /hpcc-dev/build --parallel $(nproc) --target package" 
+            # docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "cmake --build /hpcc-dev/build --parallel $(nproc) --target package"
           done
 
       - name: CMake Containerized Packages (community)
@@ -284,7 +284,7 @@ jobs:
           JF_URL: https://${{ secrets.JFROG_REGISTRY }}
           JF_USER: ${{ secrets.JFROG_USERNAME }}
           JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
-          
+
       - name: CMake Packages (internal)
         if: ${{ matrix.ln && !matrix.container && !matrix.documentation }}
         run: |
@@ -296,9 +296,9 @@ jobs:
             sudo rm -rf ${{ needs.preamble.outputs.folder_build }}/CMakeFiles
             docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_ln }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "${{ needs.preamble.outputs.gpg_import }} && \
               cmake -S /hpcc-dev/LN -B /hpcc-dev/build -DHPCC_SOURCE_DIR=/hpcc-dev/HPCC-Platform ${{ needs.preamble.outputs.cmake_docker_config }} -DSIGN_MODULES_PASSPHRASE=${{ secrets.SIGN_MODULES_PASSPHRASE }} -DSIGN_MODULES_KEYID=${{ secrets.SIGN_MODULES_KEYID }} -D$plugin=ON -DINCLUDE_PLUGINS=ON -DCONTAINERIZED=OFF -DSUPPRESS_REMBED=ON -DSUPPRESS_V8EMBED=ON -DSUPPRESS_SPARK=ON -DCPACK_STRIP_FILES=OFF ${{ matrix.cmake_options_extra }} && \
-              cmake --build /hpcc-dev/build --parallel $(nproc) --target package" 
+              cmake --build /hpcc-dev/build --parallel $(nproc) --target package"
             # Disabled as not currently needed ---
-            # docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_ln }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "cmake -S /hpcc-dev/LN -B /hpcc-dev/build -DHPCC_SOURCE_DIR=/hpcc-dev/HPCC-Platform ${{ needs.preamble.outputs.cmake_docker_config }} -DINCLUDE_PLUGINS=ON -DCONTAINERIZED=OFF -DSUPPRESS_REMBED=ON -DSUPPRESS_V8EMBED=ON -DSUPPRESS_SPARK=ON -DCPACK_STRIP_FILES=ON" 
+            # docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_ln }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "cmake -S /hpcc-dev/LN -B /hpcc-dev/build -DHPCC_SOURCE_DIR=/hpcc-dev/HPCC-Platform ${{ needs.preamble.outputs.cmake_docker_config }} -DINCLUDE_PLUGINS=ON -DCONTAINERIZED=OFF -DSUPPRESS_REMBED=ON -DSUPPRESS_V8EMBED=ON -DSUPPRESS_SPARK=ON -DCPACK_STRIP_FILES=ON"
             # docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_ln }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "cmake --build /hpcc-dev/build --parallel $(nproc) --target package"
           done
 
@@ -311,10 +311,10 @@ jobs:
           sudo rm -rf ${{ needs.preamble.outputs.folder_build }}/CMakeFiles
           docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_ln }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "${{ needs.preamble.outputs.gpg_import }} && \
             cmake -S /hpcc-dev/LN -B /hpcc-dev/build -DHPCC_SOURCE_DIR=/hpcc-dev/HPCC-Platform ${{ needs.preamble.outputs.cmake_docker_config }} -DSIGN_MODULES_PASSPHRASE=${{ secrets.SIGN_MODULES_PASSPHRASE }} -DSIGN_MODULES_KEYID=${{ secrets.SIGN_MODULES_KEYID }} -DINCLUDE_PLUGINS=ON -DCONTAINERIZED=ON -DSUPPRESS_REMBED=ON -DSUPPRESS_V8EMBED=ON -DSUPPRESS_SPARK=ON -DCPACK_STRIP_FILES=OFF ${{ matrix.cmake_options_extra }} && \
-            cmake --build /hpcc-dev/build --parallel $(nproc) --target package" 
+            cmake --build /hpcc-dev/build --parallel $(nproc) --target package"
           docker run --rm --mount ${{ needs.preamble.outputs.mount_platform }} --mount ${{ needs.preamble.outputs.mount_ln }} --mount ${{ needs.preamble.outputs.mount_build }} ${{ steps.vars.outputs.docker_tag_candidate_base }} "${{ needs.preamble.outputs.gpg_import }} && \
             cmake -S /hpcc-dev/LN -B /hpcc-dev/build -DHPCC_SOURCE_DIR=/hpcc-dev/HPCC-Platform ${{ needs.preamble.outputs.cmake_docker_config }} -DSIGN_MODULES_PASSPHRASE=${{ secrets.SIGN_MODULES_PASSPHRASE }} -DSIGN_MODULES_KEYID=${{ secrets.SIGN_MODULES_KEYID }} -DINCLUDE_PLUGINS=ON -DCONTAINERIZED=ON -DSUPPRESS_REMBED=ON -DSUPPRESS_V8EMBED=ON -DSUPPRESS_SPARK=ON -DCPACK_STRIP_FILES=ON ${{ matrix.cmake_options_extra }} && \
-            cmake --build /hpcc-dev/build --parallel $(nproc) --target package" 
+            cmake --build /hpcc-dev/build --parallel $(nproc) --target package"
 
       - name: Upload Assets (internal)
         if: ${{ matrix.ln }}
@@ -427,6 +427,22 @@ jobs:
           submodules: recursive
           path: ./LN
 
+      - name: "Create code signing"
+        shell: "pwsh"
+        env:
+          SIGN_CERT: ${{ secrets.SIGN_CERT }}
+          SIGN_PW: ${{ secrets.SIGN_PW }}
+        run: |
+          mkdir -p ./sign
+          cd sign
+          $pfxPath = "hpcc_code_signing.pfx"
+          $encodedBytes = [System.Convert]::FromBase64String($env:SIGN_CERT)
+          $currentDirectory = Get-Location
+          $certificatePath = Join-Path -Path $currentDirectory -ChildPath $pfxPath
+          [IO.File]::WriteAllBytes("$certificatePath", $encodedBytes)
+          echo ${env:SIGN_PW} > passphrase.txt
+          CertUtil -p ${env:SIGN_PW} hpcc_code_signing.pfx
+
       - name: "vcpkg Bootstrap"
         shell: "bash"
         run: |
@@ -450,6 +466,14 @@ jobs:
           cmake -S ./HPCC-Platform -B ./build ${{ matrix.cmake_config_options }}
           cmake --build ./build ${{ matrix.cmake_build_options }} --target package
 
+      - name: Sign Packages
+        shell: "pwsh"
+        env:
+          SIGN_PW: ${{ secrets.SIGN_PW }}
+        run: |
+          cd ./build
+          C:\"Program Files (x86)"\"Microsoft SDKs"\ClickOnce\SignTool\signtool.exe sign /debug /f ../sign/hpcc_code_signing.pfx /p $env:SIGN_PW /t http://timestamp.digicert.com /fd SHA256 hpccsystems-clienttools*.exe
+
       - name: Upload Assets
         uses: ncipollo/release-action@v1.12.0
         with:
@@ -465,6 +489,14 @@ jobs:
           ${{ matrix.sudo }} rm -rf ./build/CMakeFiles
           cmake -S ./LN -B ./build ${{ matrix.cmake_config_options }}
           cmake --build ./build ${{ matrix.cmake_build_options }} --target package
+
+      - name: Sign LN Package
+        shell: "pwsh"
+        env:
+          SIGN_PW: ${{ secrets.SIGN_PW }}
+        run: |
+          cd ./build
+          C:\"Program Files (x86)"\"Microsoft SDKs"\ClickOnce\SignTool\signtool.exe sign /debug /f ../sign/hpcc_code_signing.pfx /p $env:SIGN_PW /t http://timestamp.digicert.com /fd SHA256 hpccsystems-clienttools*.exe
 
       - name: Upload LN Assets
         uses: ncipollo/release-action@v1.12.0
@@ -484,3 +516,121 @@ jobs:
         with:
           name: ${{ matrix.os }}-logs
           path: ./build/**/*.log
+
+  build-bare-metal-eclide:
+    name: Build Bare Metal ECLIDE
+    needs: [ preamble, build-docker, build-bare-metal ]
+    runs-on: "windows-2022"
+    steps:
+      - name: Print vars
+        shell: "bash"
+        run: |
+          echo "${{ toJSON(needs.preamble.outputs) }})"
+
+      - name: Checkout HPCC-Platform
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ needs.preamble.outputs.community_ref }}
+          submodules: recursive
+          path: ./HPCC-Platform
+
+      - name: Checkout ECLIDE
+        uses: actions/checkout@v3
+        with:
+          repository: ${{ github.repository_owner }}/ECLIDE
+          ref: ${{ needs.preamble.outputs.eclide_ref }}
+          submodules: recursive
+          path: ./ECLIDE
+          fetch-depth: 0
+
+      - name: "Install html-help-workshop"
+        shell: "bash"
+        run: |
+          choco install html-help-workshop
+          mkdir -p ./ECLIDE/docs }}
+
+      - name: "Create EN_US CHM file"
+        shell: "bash"
+        run: |
+          dep_tag="${{ needs.preamble.outputs.community_tag }}"
+          hpcc_version="${{ needs.preamble.outputs.hpcc_version }}"
+          curl -sL -o html_help_EN_US.zip https://github.com/hpcc-systems/HPCC-Platform/releases/download/${dep_tag}/html_help_EN_US-${hpcc_version}.zip
+          7z x html_help_EN_US.zip
+          mv html_help html_help_EN_US
+          cd html_help_EN_US
+          # Chocolate install a package but it is not in PATH variable. Use path full of hhc.exe
+          # hhc.exe return non-zero. Appending "true" to work-around
+          C:/"Program Files (x86)"/"HTML Help Workshop"/hhc.exe htmlhelp.hhp || true
+          mv htmlhelp.chm ECLReference.chm
+          cp ECLReference.chm ../ECLIDE/docs/
+
+      - name: "Create PT_BR CHM file"
+        shell: "bash"
+        run: |
+          dep_tag="${{ needs.preamble.outputs.community_tag }}"
+          hpcc_version="${{ needs.preamble.outputs.hpcc_version }}"
+          curl -sL -o html_help_PT_BR.zip https://github.com/hpcc-systems/HPCC-Platform/releases/download/${dep_tag}/html_help_PT_BR-${hpcc_version}.zip
+          7z x html_help_PT_BR.zip
+          mv html_help html_help_PT_BR
+          cd html_help_PT_BR
+          # Chocolate install a package but it is not in PATH variable. Use path full of hhc.exe
+          # hhc.exe return non-zero. Appending "true" to work-around
+          C:/"Program Files (x86)"/"HTML Help Workshop"/hhc.exe htmlhelp.hhp || true
+          mv htmlhelp.chm ECLReference_PT_BR.chm
+          cp ECLReference_PT_BR.chm ../ECLIDE/docs/
+
+      - name: "Fetch Clienttools package"
+        shell: "bash"
+        run: |
+          cd ./ECLIDE
+          mkdir HPCC-Platform
+          cd HPCC-Platform
+          dep_tag="${{ needs.preamble.outputs.community_tag }}"
+          curl -sL -o hpccsystems-clienttools-${dep_tag}Windows-x86_64.exe https://github.com/hpcc-systems/HPCC-Platform/releases/download/${dep_tag}/hpccsystems-clienttools-${dep_tag}Windows-x86_64.exe
+
+      - name: "Create code sining"
+        shell: "pwsh"
+        env:
+          SIGN_CERT: ${{ secrets.SIGN_CERT }}
+          SIGN_PW: ${{ secrets.SIGN_PW }}
+        run: |
+          mkdir -p ./sign
+          cd sign
+          $pfxPath = "hpcc_code_signing.pfx"
+          $encodedBytes = [System.Convert]::FromBase64String($env:SIGN_CERT)
+          $currentDirectory = Get-Location
+          $certificatePath = Join-Path -Path $currentDirectory -ChildPath $pfxPath
+          [IO.File]::WriteAllBytes("$certificatePath", $encodedBytes)
+          echo ${env:SIGN_PW} > passphrase.txt
+          CertUtil -p ${env:SIGN_PW} hpcc_code_signing.pfx
+
+      - name: "Build ECLIDE"
+        run: |
+          cd ECLIDE
+          mkdir -p ./build
+          cd ./build
+          cmake -A Win32 -S ../ -B .
+          cmake --build . --config RelWithDebInfo --target package --parallel
+
+      - name: Sign ECLIDE Package
+        shell: "pwsh"
+        env:
+          SIGN_PW: ${{ secrets.SIGN_PW }}
+        run: |
+          cd ./ECLIDE/build
+          C:\"Program Files (x86)"\"Microsoft SDKs"\ClickOnce\SignTool\signtool.exe sign /debug /f ../../sign/hpcc_code_signing.pfx /p $env:SIGN_PW /t http://timestamp.digicert.com /fd SHA256 hpccsystems-eclide*.exe
+
+      - name: Upload Assets
+        uses: ncipollo/release-action@v1.12.0
+        with:
+          allowUpdates: true
+          generateReleaseNotes: false
+          prerelease: ${{ contains(github.ref, '-rc') }}
+          artifacts: "./ECLIDE/build/*.exe"
+
+      - name: Upload error logs
+        if: ${{ failure() || cancelled() }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: windows-2022-logs
+          path: ./ECLIDE/build/**/*.log
